In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
%matplotlib inline
import numpy as np

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
data=pd.read_csv('orders.csv')

In [4]:
data.columns

Index(['Order Id', 'Order Date', 'Ship Mode', 'Segment', 'Country', 'City',
       'State', 'Postal Code', 'Region', 'Category', 'Sub Category',
       'Product Id', 'cost price', 'List Price', 'Quantity',
       'Discount Percent'],
      dtype='object')

In [5]:
df=pd.read_csv('orders.csv',na_values=['Not Available','unknown'])
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [6]:
df.rename(columns={'Order ID' : 'order_id', 'City' : 'city'})
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')

In [7]:
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [8]:
df['discount']=df['list_price']*df['discount_percent']*0.1
df['sale_price']=df['list_price']-df['discount']
df['profit']=df['sale_price']-df['cost_price']
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,52.0,208.0,-32.0
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,219.0,511.0,-89.0
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,5.0,5.0,-5.0
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,192.0,768.0,-12.0
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,10.0,10.0,-10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,12.0,18.0,-12.0
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,36.0,54.0,-16.0
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,52.0,208.0,-12.0
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,9.0,21.0,-9.0
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,72.0,168.0,-42.0

In [9]:
df['order_date']=pd.to_datetime(df['order_date'],format="%Y-%m-%d")

In [10]:
df.drop(['list_price', 'cost_price', 'discount_percent'],axis=1, inplace=True)

# Print the updated dataframe
print(df)

      order_id order_date       ship_mode    segment        country  \
0            1 2023-03-01    Second Class   Consumer  United States
1            2 2023-08-15    Second Class   Consumer  United States
2            3 2023-01-10    Second Class  Corporate  United States
3            4 2022-06-18  Standard Class   Consumer  United States
4            5 2022-07-13  Standard Class   Consumer  United States
...        ...        ...             ...        ...            ...
9989      9990 2023-02-18    Second Class   Consumer  United States
9990      9991 2023-03-17  Standard Class   Consumer  United States
9991      9992 2022-08-07  Standard Class   Consumer  United States
9992      9993 2022-11-19  Standard Class   Consumer  United States
9993      9994 2022-07-17    Second Class   Consumer  United States

                 city       state  postal_code region         category  \
0           Henderson    Kentucky        42420  South        Furniture
1           Henderson    Kentucky        42420  South        Furniture
2         Los Angeles  California        90036   West  Office Supplies
3     Fort Lauderdale     Florida        33311  South        Furniture
4     Fort Lauderdale     Florida        33311  South  Office Supplies
...               ...         ...          ...    ...              ...
9989            Miami     Florida        33180  South        Furniture
9990       Costa Mesa  California        92627   West        Furniture
9991       Costa Mesa  California        92627   West       Technology
9992       Costa Mesa  California        92627   West  Office Supplies
9993      Westminster  California        92683   West  Office Supplies

     sub_category       product_id  quantity  discount  sale_price  profit
0       Bookcases  FUR-BO-10001798         2      52.0       208.0   -32.0
1          Chairs  FUR-CH-10000454         3     219.0       511.0   -89.0
2          Labels  OFF-LA-10000240         2       5.0         5.0    -5.0
3          Tables  FUR-TA-10000577         5     192.0       768.0   -12.0
4         Storage  OFF-ST-10000760         2      10.0        10.0   -10.0
...           ...              ...       ...       ...         ...     ...
9989  Furnishings  FUR-FU-10001889         3      12.0        18.0   -12.0
9990  Furnishings  FUR-FU-10000747         2      36.0        54.0   -16.0
9991       Phones  TEC-PH-10003645         2      52.0       208.0   -12.0
9992        Paper  OFF-PA-10004041         4       9.0        21.0    -9.0
9993   Appliances  OFF-AP-10002684         2      72.0       168.0   -42.0

[9994 rows x 16 columns]

In [11]:
pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in d:\jupiter\lib\site-packages (1.1.1)
Requirement already satisfied: sqlalchemy in d:\jupiter\lib\site-packages (2.0.25)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\jupiter\lib\site-packages (from sqlalchemy) (4.9.0)
Requirement already satisfied: greenlet!=0.4.17 in d:\jupiter\lib\site-packages (from sqlalchemy) (3.0.1)
Note: you may need to restart the kernel to use updated packages.

In [13]:
import pymysql
from sqlalchemy import create_engine

# Connection details
username = 'root'
password = 'root'
server = 'localhost'
port = '3306'
dbname = 'sakila'

# Create the connection URL
connection_url = f'mysql+pymysql://{username}:{password}@{server}:{port}/{dbname}'

# Create the engine
engine = create_engine(connection_url)

# Test the connection
try:
    connection = engine.connect()
    print("Connection successful!")
    connection.close()
except Exception as e:
    print(f"Connection failed: {e}")

Connection successful!

In [14]:
df.to_sql('df_orders',con=engine,index=False, if_exists='append')

9994